### ISSUE TITLE
Definição de função junto com declaração de variáveis globais

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#1]
https://github.com/guipleite/Embarcados-LavaRoupa/blob/149eb37bc884ceef4cec07b5d0966c00172e31d6/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L54-L79

Ideal seria funções estar após variáveis globais

**Comment by guipleite** [comment]
Corrigido no commit: https://github.com/guipleite/Embarcados-LavaRoupa/commit/ab51826d77329b80734774b3d857a43002085f88
