### ISSUE TITLE
Números mágicos de coordenada. Ideal seria arquivo separado com define gui.h para customizar.

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#11]
https://github.com/guipleite/Embarcados-LavaRoupa/blob/149eb37bc884ceef4cec07b5d0966c00172e31d6/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L512

**Comment by guipleite** [comment]
Corrigido no commit : https://github.com/guipleite/Embarcados-LavaRoupa/commit/ab51826d77329b80734774b3d857a43002085f88#diff-1e19ca7e1ec75a7f911a59c65bd75a6c
