### ISSUE TITLE
Código morto / comentado

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#13]
https://github.com/guipleite/Embarcados-LavaRoupa/blob/149eb37bc884ceef4cec07b5d0966c00172e31d6/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L599

Ideal é remover, se precisar, recuperar via git

**Comment by guipleite** [comment]
removido no commit: https://github.com/guipleite/Embarcados-LavaRoupa/commit/ab51826d77329b80734774b3d857a43002085f88
