### ISSUE TITLE
Cenário 2 não é atendido

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#16]
Não é exibido o progresso/tempo restante da lavagem.

**Comment by guipleite** [comment]
O tempo restante e progresso são mostrados na tela de lavagem, como mostra a imagem:

[https://github.com/guipleite/Embarcados-LavaRoupa/blob/master/interface.jpg](url)

**Comment by eduardomarossi** [comment]
O botão atrapalhou a visibilidade. Tudo bem, está ok.
