### ISSUE TITLE
Variáveis não estão sendo usadas em interrupção, não é necessário usar volatile.

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#2]
https://github.com/guipleite/Embarcados-LavaRoupa/blob/149eb37bc884ceef4cec07b5d0966c00172e31d6/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L77-L79

**Comment by guipleite** [comment]
Corrigido no commit: https://github.com/guipleite/Embarcados-LavaRoupa/commit/720c637d3dc425709d306da4bf29a003cb1f4cba#diff-1e19ca7e1ec75a7f911a59c65bd75a6c
