### ISSUE TITLE
Só utiliza interrupção de alarme, não precisa verificar condição de incremento do RTT

### ISSUE THREAD

**Issue by eduardomarossi** [guipleite/Embarcados-LavaRoupa#4]
https://github.com/guipleite/Embarcados-LavaRoupa/blob/149eb37bc884ceef4cec07b5d0966c00172e31d6/LCD-maxTouch-Switch-Toggle/MXT_EXAMPLE_USART1/src/main.c#L90

**Comment by guipleite** [comment]
Corrgido no commit :https://github.com/guipleite/Embarcados-LavaRoupa/commit/720c637d3dc425709d306da4bf29a003cb1f4cba
